# Generated by Django 4.1.5 on 2023-01-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookingform',
        ),
    ]
