# Generated by Django 4.1.5 on 2023-01-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_rename_booking_bookingform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('days', models.IntegerField()),
                ('startpoint', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookingform',
        ),
    ]
