# Generated by Django 4.1.5 on 2023-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_bookingform_delete_bookingforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='persons',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
