# Generated by Django 4.1.5 on 2023-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_alter_bookingform_days_alter_bookingform_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
