# Generated by Django 4.1.5 on 2023-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_bookingform_date_alter_bookingform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='date',
            field=models.DateField(),
        ),
    ]
